// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZVLnGGfot1ieg7C681sThNoOonM_FL_s',
    appId: '1:1033063893602:web:c6a603e7b4f114829a5f3b',
    messagingSenderId: '1033063893602',
    projectId: 'taskhub-paramadina',
    authDomain: 'taskhub-paramadina.firebaseapp.com',
    storageBucket: 'taskhub-paramadina.firebasestorage.app',
    measurementId: 'G-R8RZT9QRRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfjtIYPSRJAJFHJqmEx61yMsWQPUMWSLM',
    appId: '1:1033063893602:android:e3751abf5d3fccb39a5f3b',
    messagingSenderId: '1033063893602',
    projectId: 'taskhub-paramadina',
    storageBucket: 'taskhub-paramadina.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJFocxtJdNOq-0zFHywGwvoXt-uNfgcos',
    appId: '1:1033063893602:ios:331fc1179df7144c9a5f3b',
    messagingSenderId: '1033063893602',
    projectId: 'taskhub-paramadina',
    storageBucket: 'taskhub-paramadina.firebasestorage.app',
    androidClientId: '1033063893602-bb7nkb6qda2e4f9or4mhlur4me0u7gla.apps.googleusercontent.com',
    iosClientId: '1033063893602-5clif3tncuctiuplvo0f2oiad3mpi32q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTaskhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJFocxtJdNOq-0zFHywGwvoXt-uNfgcos',
    appId: '1:1033063893602:ios:331fc1179df7144c9a5f3b',
    messagingSenderId: '1033063893602',
    projectId: 'taskhub-paramadina',
    storageBucket: 'taskhub-paramadina.firebasestorage.app',
    androidClientId: '1033063893602-bb7nkb6qda2e4f9or4mhlur4me0u7gla.apps.googleusercontent.com',
    iosClientId: '1033063893602-5clif3tncuctiuplvo0f2oiad3mpi32q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTaskhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZVLnGGfot1ieg7C681sThNoOonM_FL_s',
    appId: '1:1033063893602:web:02a333d20d4fa0499a5f3b',
    messagingSenderId: '1033063893602',
    projectId: 'taskhub-paramadina',
    authDomain: 'taskhub-paramadina.firebaseapp.com',
    storageBucket: 'taskhub-paramadina.firebasestorage.app',
    measurementId: 'G-35DXQF9W3G',
  );
}
