import 'package:flutter_taskhub/models/notification.dart';
import 'package:flutter_taskhub/models/task.dart';
import 'notification_api_service.dart';
import 'supabase_notification_service.dart';

enum NotificationBackend { api, supabase }

class NotificationService {
  final NotificationApiService _apiService = NotificationApiService();
  final SupabaseNotificationService _supabaseService = SupabaseNotificationService();

  NotificationBackend _backend = NotificationBackend.api;

  // Set the authentication token
  void setToken(String token) {
    _apiService.setToken(token);
  }

  // Set the backend to use
  void setBackend(NotificationBackend backend) {
    _backend = backend;
  }

  // Create a new notification
  Future<String> createNotification(Notification notification) async {
    try {
      if (_backend == NotificationBackend.api) {
        return await _apiService.createNotification(notification);
      } else {
        return await _supabaseService.createNotification(notification);
      }
    } catch (e) {
      throw Exception('Failed to create notification: $e');
    }
  }

  // Get all notifications for a specific user
  // Note: This would typically return a Stream in a real implementation
  // For now, returning a Future since HTTP requests are one-time
  Future<List<Notification>> getUserNotifications(String userId) async {
    try {
      if (_backend == NotificationBackend.api) {
        return await _apiService.getUserNotifications();
      } else {
        // For Supabase, use the non-stream method
        return await _supabaseService.getUserNotificationsOnce(userId);
      }
    } catch (e) {
      throw Exception('Failed to get notifications: $e');
    }
  }

  // Get unread notifications count for a user
  Future<int> getUnreadNotificationsCount(String userId) async {
    try {
      if (_backend == NotificationBackend.api) {
        return await _apiService.getUnreadNotificationsCount();
      } else {
        return await _supabaseService.getUnreadNotificationsCount(userId);
      }
    } catch (e) {
      throw Exception('Failed to get unread notifications count: $e');
    }
  }

  // Mark a notification as read
  Future<void> markNotificationAsRead(String notificationId) async {
    try {
      if (_backend == NotificationBackend.api) {
        await _apiService.markNotificationAsRead(notificationId);
      } else {
        await _supabaseService.markNotificationAsRead(notificationId);
      }
    } catch (e) {
      throw Exception('Failed to mark notification as read: $e');
    }
  }

  // Mark all notifications as read for a user
  Future<void> markAllNotificationsAsRead(String userId) async {
    try {
      if (_backend == NotificationBackend.api) {
        await _apiService.markAllNotificationsAsRead(userId);
      } else {
        await _supabaseService.markAllNotificationsAsRead(userId);
      }
    } catch (e) {
      throw Exception('Failed to mark all notifications as read: $e');
    }
  }

  // Create a group join notification
  Future<String> createGroupJoinNotification({
    required String userId,
    required String groupId,
    required String groupName,
  }) async {
    if (_backend == NotificationBackend.api) {
      final notification = Notification(
        id: '', // Will be generated by API
        userId: userId,
        title: 'Group Invitation',
        message: 'You have been added to the group: $groupName',
        type: NotificationType.groupJoin,
        data: GroupNotificationData(
          groupId: groupId,
          groupName: groupName,
        ).toMap(),
        isRead: false,
        createdAt: DateTime.now(),
      );

      return await createNotification(notification);
    } else {
      return await _supabaseService.createGroupJoinNotification(
        userId: userId,
        groupId: groupId,
        groupName: groupName,
      );
    }
  }

  // Create a task deadline notification
  Future<String> createTaskDeadlineNotification({
    required String userId,
    required Task task,
    required String groupName,
    required String timeRemaining,
  }) async {
    if (_backend == NotificationBackend.api) {
      final notification = Notification(
        id: '', // Will be generated by API
        userId: userId,
        title: 'Task Deadline Approaching',
        message: 'Task "${task.title}" in group "$groupName" is due in $timeRemaining',
        type: NotificationType.taskDeadline,
        data: TaskNotificationData(
          taskId: task.id,
          taskTitle: task.title,
          groupId: task.groupId,
          groupName: groupName,
          dueDate: task.dueDate,
        ).toMap(),
        isRead: false,
        createdAt: DateTime.now(),
      );

      return await createNotification(notification);
    } else {
      return await _supabaseService.createTaskDeadlineNotification(
        userId: userId,
        task: task,
        groupName: groupName,
        timeRemaining: timeRemaining,
      );
    }
  }

  // Create a task assignment notification
  Future<String> createTaskAssignmentNotification({
    required String userId,
    required Task task,
    required String groupName,
  }) async {
    if (_backend == NotificationBackend.api) {
      final notification = Notification(
        id: '', // Will be generated by API
        userId: userId,
        title: 'Task Assigned',
        message: 'You have been assigned to task: ${task.title} in group $groupName',
        type: NotificationType.taskAssignment,
        data: TaskNotificationData(
          taskId: task.id,
          taskTitle: task.title,
          groupId: task.groupId,
          groupName: groupName,
          dueDate: task.dueDate,
        ).toMap(),
        isRead: false,
        createdAt: DateTime.now(),
      );

      return await createNotification(notification);
    } else {
      return await _supabaseService.createTaskAssignmentNotification(
        userId: userId,
        task: task,
        groupName: groupName,
      );
    }
  }

  // Create a group created notification
  Future<String> createGroupCreatedNotification({
    required String userId,
    required String groupId,
    required String groupName,
  }) async {
    if (_backend == NotificationBackend.api) {
      final notification = Notification(
        id: '', // Will be generated by API
        userId: userId,
        title: 'Group Created',
        message: 'New group created: $groupName',
        type: NotificationType.groupCreated,
        data: GroupNotificationData(
          groupId: groupId,
          groupName: groupName,
        ).toMap(),
        isRead: false,
        createdAt: DateTime.now(),
      );

      return await createNotification(notification);
    } else {
      return await _supabaseService.createGroupCreatedNotification(
        userId: userId,
        groupId: groupId,
        groupName: groupName,
      );
    }
  }

  // Create a task created notification
  Future<String> createTaskCreatedNotification({
    required String userId,
    required Task task,
    required String groupName,
  }) async {
    if (_backend == NotificationBackend.api) {
      final notification = Notification(
        id: '', // Will be generated by API
        userId: userId,
        title: 'Task Created',
        message: 'New task created: ${task.title} in group $groupName',
        type: NotificationType.taskCreated,
        data: TaskNotificationData(
          taskId: task.id,
          taskTitle: task.title,
          groupId: task.groupId,
          groupName: groupName,
          dueDate: task.dueDate,
        ).toMap(),
        isRead: false,
        createdAt: DateTime.now(),
      );

      return await createNotification(notification);
    } else {
      return await _supabaseService.createTaskCreatedNotification(
        userId: userId,
        task: task,
        groupName: groupName,
      );
    }
  }
}