import 'dart:async';
import 'package:flutter_taskhub/models/notification.dart' as app_notification;
import 'package:flutter_taskhub/models/task.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class SupabaseNotificationService {
  final SupabaseClient _supabase = Supabase.instance.client;

  // Get all notifications for the current user (non-stream version)
  Future<List<app_notification.Notification>> getUserNotificationsOnce(String userId) async {
    final response = await _supabase
        .from('notifications')
        .select()
        .eq('user_id', userId)
        .order('created_at', ascending: false);

    return (response as List)
        .map((map) => app_notification.Notification.fromJson(map as Map<String, dynamic>))
        .toList();
  }

  // Create a new notification
  Future<String> createNotification(app_notification.Notification notification) async {
    final response = await _supabase
        .from('notifications')
        .insert({
          'user_id': notification.userId,
          'title': notification.title,
          'message': notification.message,
          'type': _mapNotificationTypeToString(notification.type),
          'data': notification.data,
          'is_read': notification.isRead,
          'created_at': notification.createdAt.toIso8601String(),
          'updated_at': notification.updatedAt?.toIso8601String(),
        })
        .select();

    final insertedNotification = response[0];
    return insertedNotification['id'];
  }

  // For real-time updates, we'll use a polling approach
  Stream<List<app_notification.Notification>> getUserNotifications(String userId) {
    // This creates a polling stream that fetches notifications every 30 seconds
    return Stream.periodic(const Duration(seconds: 30))
        .asyncMap((_) => getUserNotificationsOnce(userId));
  }

  // Get unread notifications count for a user
  Future<int> getUnreadNotificationsCount(String userId) async {
    final response = await _supabase
        .from('notifications')
        .select('id')
        .eq('user_id', userId)
        .eq('is_read', false);

    return (response as List).length;
  }


  // Mark a notification as read
  Future<void> markNotificationAsRead(String notificationId) async {
    await _supabase
        .from('notifications')
        .update({'is_read': true, 'updated_at': DateTime.now().toIso8601String()})
        .eq('id', notificationId);
  }

  // Mark all notifications as read for a user
  // In a real implementation, you would get the user ID from the authentication context
  Future<void> markAllNotificationsAsRead(String userId) async {
    await _supabase
        .from('notifications')
        .update({'is_read': true, 'updated_at': DateTime.now().toIso8601String()})
        .eq('user_id', userId)
        .eq('is_read', false);
  }

  // Helper method to map notification type to string
  String _mapNotificationTypeToString(app_notification.NotificationType type) {
    switch (type) {
      case app_notification.NotificationType.groupJoin:
        return 'group_join';
      case app_notification.NotificationType.taskDeadline:
        return 'task_deadline';
      case app_notification.NotificationType.taskAssignment:
        return 'task_assignment';
      case app_notification.NotificationType.taskUpdate:
        return 'task_update';
      case app_notification.NotificationType.groupCreated:
        return 'group_created';
      case app_notification.NotificationType.taskCreated:
        return 'task_created';
      case app_notification.NotificationType.other:
        return 'other';
    }
  }

  // Delete a notification
  Future<void> deleteNotification(String notificationId) async {
    await _supabase.from('notifications').delete().eq('id', notificationId);
  }

  // Create a group join notification
  Future<String> createGroupJoinNotification({
    required String userId,
    required String groupId,
    required String groupName,
  }) async {
    final notification = app_notification.Notification(
      id: '', // Will be generated by Supabase
      userId: userId,
      title: 'Group Invitation',
      message: 'You have been added to the group: $groupName',
      type: app_notification.NotificationType.groupJoin,
      data: {
        'group_id': groupId,
        'group_name': groupName,
      },
      isRead: false,
      createdAt: DateTime.now(),
    );

    return await createNotification(notification);
  }

  // Create a task deadline notification
  Future<String> createTaskDeadlineNotification({
    required String userId,
    required Task task,
    required String groupName,
    required String timeRemaining,
  }) async {
    final notification = app_notification.Notification(
      id: '', // Will be generated by Supabase
      userId: userId,
      title: 'Task Deadline Approaching',
      message: 'Task "${task.title}" in group "$groupName" is due in $timeRemaining',
      type: app_notification.NotificationType.taskDeadline,
      data: {
        'task_id': task.id,
        'task_title': task.title,
        'group_id': task.groupId,
        'group_name': groupName,
        'due_date': task.dueDate?.toIso8601String(),
      },
      isRead: false,
      createdAt: DateTime.now(),
    );

    return await createNotification(notification);
  }

  // Create a task assignment notification
  Future<String> createTaskAssignmentNotification({
    required String userId,
    required Task task,
    required String groupName,
  }) async {
    final notification = app_notification.Notification(
      id: '', // Will be generated by Supabase
      userId: userId,
      title: 'Task Assigned',
      message: 'You have been assigned to task: ${task.title} in group $groupName',
      type: app_notification.NotificationType.taskAssignment,
      data: {
        'task_id': task.id,
        'task_title': task.title,
        'group_id': task.groupId,
        'group_name': groupName,
        'due_date': task.dueDate?.toIso8601String(),
      },
      isRead: false,
      createdAt: DateTime.now(),
    );

    return await createNotification(notification);
  }

  // Create a group created notification
  Future<String> createGroupCreatedNotification({
    required String userId,
    required String groupId,
    required String groupName,
  }) async {
    final notification = app_notification.Notification(
      id: '', // Will be generated by Supabase
      userId: userId,
      title: 'Group Created',
      message: 'New group created: $groupName',
      type: app_notification.NotificationType.groupCreated,
      data: {
        'group_id': groupId,
        'group_name': groupName,
      },
      isRead: false,
      createdAt: DateTime.now(),
    );

    return await createNotification(notification);
  }

  // Create a task created notification
  Future<String> createTaskCreatedNotification({
    required String userId,
    required Task task,
    required String groupName,
  }) async {
    final notification = app_notification.Notification(
      id: '', // Will be generated by Supabase
      userId: userId,
      title: 'Task Created',
      message: 'New task created: ${task.title} in group $groupName',
      type: app_notification.NotificationType.taskCreated,
      data: {
        'task_id': task.id,
        'task_title': task.title,
        'group_id': task.groupId,
        'group_name': groupName,
        'due_date': task.dueDate?.toIso8601String(),
      },
      isRead: false,
      createdAt: DateTime.now(),
    );

    return await createNotification(notification);
  }
}